--9장

--단일행 서브쿼리

SELECT *
FROM EMP;

SELECT SAL
FROM EMP
WHERE ENAME='JONES';

SELECT *
FROM EMP
WHERE SAL > 2975;

SELECT *
FROM EMP
WHERE SAL > (SELECT SAL
FROM EMP
WHERE ENAME='JONES');


SELECT *
FROM EMP
WHERE HIREDATE < (SELECT HIREDATE
FROM EMP
WHERE ENAME = 'SCOTT');

SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.DEPTNO = 20
AND E.SAL > (SELECT AVG(SAL)
FROM EMP);

--다중행 서브쿼리
--IN연산자

SELECT *
FROM EMP;

SELECT *
FROM EMP
WHERE SAL IN (SELECT MAX(SAL)
FROM EMP
GROUP BY DEPTNO);

--ANY, SOME 연산자
--조건식을 대입한 결과가 하나라도 TRUE일 경우, 메인쿼리의 조건식이 TRUE

SELECT SAL
FROM EMP
WHERE DEPTNO = 30;

SELECT *
FROM EMP
WHERE SAL > ANY (SELECT SAL
FROM EMP
WHERE DEPTNO = 30);

SELECT *
FROM EMP
WHERE SAL < ANY (SELECT SAL
FROM EMP
WHERE DEPTNO = 30);

SELECT *
FROM EMP
WHERE SAL > SOME (SELECT SAL
FROM EMP
WHERE DEPTNO = 30);

SELECT *
FROM EMP
WHERE SAL < SOME (SELECT SAL
FROM EMP
WHERE DEPTNO = 30);

--ALL 연산자
--조건식을 대입한 결과 모두가 TRUE여야함

SELECT *
FROM EMP
WHERE SAL > ALL (SELECT SAL
FROM EMP
WHERE DEPTNO = 30);

SELECT *
FROM EMP
WHERE SAL < ALL (SELECT SAL
FROM EMP
WHERE DEPTNO = 30);

--EXISTS연산자
--결과 존재 시 TRUE / 없을 시 FALSE 출력

SELECT *
FROM DEPT; 

SELECT *
FROM EMP
WHERE EXISTS (SELECT DNAME
FROM DEPT
WHERE DEPTNO = 10);

SELECT *
FROM EMP
WHERE EXISTS (SELECT DNAME
FROM DEPT
WHERE DEPTNO = 90);

--SELECT절에 사용하는 서브쿼리

SELECT * FROM SALGRADE;
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT EMPNO, ENAME, JOB, SAL,
(SELECT GRADE
FROM SALGRADE
WHERE E.SAL BETWEEN LOSAL AND HISAL)AS SALGRADE,
DEPTNO,
(SELECT DNAME
FROM DEPT
WHERE E.DEPTNO = DEPT.DEPTNO)AS DNAME
FROM EMP E;