--DML 명령어


CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP;

--INSERT INTO 테이블(테이블값)
--VALUES (지정값)
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (50,'DATABASE','SEOUL');

SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP
VALUES(60,'NETWORK','BUSAN');
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (70,'WEB',NULL);
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
VALUES(80, 'MOBILE','');
INSERT INTO DEPT_TEMP (DEPTNO, LOC)
VALUES(90,'INCHEON');

--테이블 생성(전체값 초기화)
CREATE TABLE EMP_TEMP
AS SELECT * FROM EMP
WHERE 1<>1;

SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (9999, '홍길동', 'PRESIDENT', NULL, '2001/01/01',5000,1000,10);

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1111,'성춘향','MANAGER',9999,'2001-01-05',4000,NULL,20);

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (2111, '이순신', 'MANAGER', 9999, TO_DATE('07/01/2001','DD/MM/YYYY'),4000,NULL,20);

INSERT INTO EMP_TEMP
VALUES (3111, '심청이', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1234, '이태신','ANALYST',NULL,TO_DATE('2024-02-26','YYYY/MM/DD'),2500,NULL,30); 

--서브쿼리를 이용하여 한 번에 여러 데이터 추가
INSERT INTO EMP_TEMP
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND S.GRADE = 1;

SELECT * FROM EMP_TEMP;

--CREATE : COMMIT처리(ROLLBACK 불가능)
CREATE TABLE DEPT_TEMP2
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP2;

--UPDATE [변경테이블]
--SET [변경할 열1]=[데이터], [변경할 열2]=[데이터], ... ,[변경할 열N]=[데이터]

UPDATE DEPT_TEMP2
SET LOC='SEOUL';

SELECT * FROM DEPT_TEMP2;
--ROLLBACK; : 직전 COMMIT 시행까지로 되돌림

ROLLBACK;

UPDATE DEPT_TEMP2
SET DNAME = 'DATABASE',
    LOC = 'SEOUL'
WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2;

--서브쿼리 이용한 데이터 수정(UPDATE)

UPDATE DEPT_TEMP2
SET(DNAME,LOC) = (SELECT DNAME,LOC
                FROM DEPT
                WHERE DEPTNO=40)
WHERE DEPTNO=40;

SELECT * FROM DEPT_TEMP2;

UPDATE DEPT_TEMP2
SET LOC = 'SEOUL'
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT_TEMP2
                WHERE DNAME = 'OPERATIONS');

SELECT * FROM DEPT_TEMP2;


CREATE TABLE EMP_TEMP2
AS SELECT * FROM EMP;


--DELETE FROM [테이블이름]
--WHERE [삭제할 대상 행을 선별하기 위한 조건식]
--데이터만 삭제

DELETE FROM EMP_TEMP2
WHERE JOB = 'MANAGER';

SELECT * FROM EMP_TEMP2;

DELETE FROM EMP_TEMP2
WHERE EMPNO IN (SELECT E.EMPNO
                FROM EMP_TEMP2 E, SALGRADE S
                WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                AND S.GRADE = 3
                AND DEPTNO = 30);
                
SELECT * FROM EMP_TEMP2;

--WHERE없이 오는 DELETE : 모든 데이터값 삭제
DELETE FROM EMP_TEMP2;

SELECT * FROM EMP_TEMP2;