-- 트랜잭션 기초
CREATE TABLE DEPT_TCL
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TCL;
--DML언어 (데이터를 사용하는 언어) -> UPDATE, DELETE, INSERT 등
INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;

DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';

SELECT * FROM DEPT_TCL;


--트랜잭션 취소 : ROLLBACK
ROLLBACK;

SELECT * FROM DEPT_TCL;

--트랜잭션 영원히 반영 : COMMIT

INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 20;

DELETE FROM DEPT_TCL WHERE DEPTNO = 40;

SELECT * FROM DEPT_TCL;

COMMIT;

SELECT * FROM DEPT_TCL;


--일관성

SELECT * FROM DEPT_TCL;
SELECT * FROM DEPT_TCL;

DELETE FROM DEPT_TCL
WHERE DEPTNO = 50;
SELECT * FROM DEPT_TCL;

COMMIT;
SELECT * FROM DEPT_TCL;
SELECT * FROM DEPT_TCL;

