--DDL명령어(CREATE)

CREATE TABLE EMP_HW(
    EMPNO   NUMBER(4),
    ENAME   VARCHAR2(10),
    JOB     VARCHAR2(9),
    MGR     NUMBER(4),
    HIREDATE    DATE,
    SAL     NUMBER(7,2),
    COMM    NUMBER(7,2),
    DEPTNO  NUMBER(2)
);

--기존 테이블 열 구조와 데이터를 복사하여 새 테이블 생성
CREATE TABLE DEPT_DDL
AS SELECT * FROM DEPT;

DESC DEPT_DDL;

SELECT * FROM DEPT_DDL;

--기존 테이블 열 구조와 일부 데이터만 복사하여 새 테이블 생성
CREATE TABLE EMP_DDL_30
AS SELECT*
FROM EMP
WHERE DEPTNO=30;

SELECT * FROM EMP_DDL_30;

--기존 테이블의 열 구조만 복사하여 새 테이블 생성
--조건식이 항상 FALSE인 WHERE절 사용하여 테이블생성
--구조만 복사하고, 데이터는 없음
CREATE TABLE EMPDEPT_DDL
AS SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,
        E.SAL,E.COMM,D.DEPTNO,D.DNAME,D.LOC
FROM EMP E, DEPT D
WHERE 1<>1;

SELECT * FROM EMPDEPT_DDL;


--ALTER / ADD : 테이블에 열 추가
CREATE TABLE EMP_ALTER
AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
ADD HP VARCHAR2(20);

SELECT * FROM EMP_ALTER;

--ALTER / RENAME A TO B : 테이블의 열 이름 변경( A -> B)

ALTER TABLE EMP_ALTER
RENAME COLUMN HP TO TEL;

SELECT * FROM EMP_ALTER;

--ALTER / MODIFY : 테이블의 열 자료형을 변경

ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(5);

DESC EMP_ALTER;

--ALTER / DROP : 테이블의 특정 열을 삭제

ALTER TABLE EMP_ALTER
DROP COLUMN TEL;

SELECT * FROM EMP_ALTER;

--TRUNCATE : 테이블의 전체 데이터를 삭제

TRUNCATE TABLE EMP_RENAME;

--DROP : 테이블 삭제
DROP TABLE EMP_RENAME;
DESC EMP_RENAME;
