-- 16-1 PL/SQL 구조
-- PL/SQL 프로그램의 기본 단위

SET SERVEROUTPUT ON;

BEGIN
  DBMS_OUTPUT.PUT_LINE('HELLO, PL/SQL!');
END;

-- 16-2 변수
DECLARE
  V_EMPNO NUMBER(4) := 7788;
  V_ENAME VARCHAR2(10);
BEGIN
  V_ENAME := 'SCOTT';
  --DBMS_OUTPUT.PUT_LINE('V_EMPNO : ' || V_EMPNO);
  DBMS_OUTPUT.PUT_LINE('V_ENAME : ' || V_ENAME);
END;

-- 상수
DECLARE
  V_TAX CONSTANT NUMBER(1) := 3;
BEGIN
  DBMS_OUTPUT.PUT_LINE('V_TAX : ' || V_TAX);
END;

--변수의 참조형
--열 참조
DECLARE
  V_DEPTNO DEPT.DEPTNO%TYPE :=50;
BEGIN
  DBMS_OUTPUT.PUT_LINE('V_DEPTNO : ' || V_DEPTNO);
END;
--행 참조
DECLARE
  V_DEPT_ROW DEPT%ROWTYPE;
BEGIN
  SELECT DEPTNO, DNAME, LOC INTO V_DEPT_ROW
  FROM DEPT
  WHERE DEPTNO = 40;
  DBMS_OUTPUT.PUT_LINE('DEPTNO : ' || V_DEPT_ROW.DEPTNO);
  DBMS_OUTPUT.PUT_LINE('DNAME : ' || V_DEPT_ROW.DNAME);
  DBMS_OUTPUT.PUT_LINE('LOC : ' || V_DEPT_ROW.LOC);
END;

-- 16-3 조건 제어문
-- IF 조건문
DECLARE
 V_NUMBER NUMBER := 13;
BEGIN
 IF MOD(V_NUMBER, 2) = 1 THEN
  DBMS_OUTPUT.PUT_LINE('V_NUMBER는 홀수입니다.');
 END IF;
END;

-- IF-THEN-ELSE
DECLARE
 V_NUMBER NUMBER := 14;
BEGIN
 IF MOD(V_NUMBER,2) = 1 THEN
  DBMS_OUTPUT.PUT_LINE('V_NUMBER는 홀수입니다.');
 ELSE
  DBMS_OUTPUT.PUT_LINE('V_NUMBER는 짝수입니다.');
 END IF;
END;

-- IF-THEN-ELSIF
DECLARE
  V_SCORE NUMBER := 87;
BEGIN
  IF V_SCORE >= 90 THEN
    DBMS_OUTPUT.PUT_LINE('A학점');
  ELSIF V_SCORE >=80 THEN
    DBMS_OUTPUT.PUT_LINE('B학점');
  ELSIF V_SCORE >= 70 THEN
    DBMS_OUTPUT.PUT_LINE('C학점');
  ELSIF V_SCORE >= 60 THEN
    DBMS_OUTPUT.PUT_LINE('D학점');
  ELSE
    DBMS_OUTPUT.PUT_LINE('F학점');
  END IF;
END;

-- CASE 조건문
DECLARE
  V_SCORE NUMBER := 87;
BEGIN
  CASE
    WHEN V_SCORE >= 90 THEN DBMS_OUTPUT.PUT_LINE('A학점');
    WHEN V_SCORE >= 80 THEN DBMS_OUTPUT.PUT_LINE('B학점');
    WHEN V_SCORE >= 70 THEN DBMS_OUTPUT.PUT_LINE('C학점');
    WHEN V_SCORE >= 60 THEN DBMS_OUTPUT.PUT_LINE('D학점');
    ELSE DBMS_OUTPUT.PUT_LINE('F학점');
  END CASE;
END;
-- 16-4 반복 제어문

SET SERVEROUTPUT ON;
SET SERVEROUTPUT OFF;

DECLARE
    V_NUM NUMBER := 0;
BEGIN
    LOOP
        DBMS_OUTPUT.PUT_LINE('현재 V_NUM : ' || V_NUM);
        V_NUM := V_NUM + 1;
        EXIT WHEN V_NUM > 4;
    END LOOP;
END;

--WHILE구문
DECLARE
    V_NUM NUMBER := 0;
BEGIN
    WHILE V_NUM < 4 LOOP
        DBMS_OUTPUT.PUT_LINE('현재 V_NUM : ' || V_NUM);
        V_NUM := V_NUM + 1;
    END LOOP;
END;

--FOR 구문

BEGIN
    FOR i IN 0..4 LOOP
        DBMS_OUTPUT.PUT_LINE('현재 i의 값 : ' || I);
    END LOOP;
END;

--CONTINUE-WHEN

BEGIN
    FOR i IN 0..4 LOOP
        CONTINUE WHEN MOD(i,2) = 1;
        DBMS_OUTPUT.PUT_LINE('현재 i의 값 : ' || I);
    END LOOP;
END;


